name: Check Vulnerabilities

on:
  pull_request:
    branches:
      - test

jobs:
  run-python:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.14'

      - name: Instalar dependencias
        run: |
          pip install -r requirements.txt

      - name: Revisar Vulnerabilidades Modelo IA
        env:
          BASE_SHA: ${{ github.event.pull_request.base.sha }}
          HEAD_SHA: ${{ github.event.pull_request.head.sha }}
        run: |
          python -m pipeline